name: "Build kernels"
on:
  workflow_dispatch:
    inputs:
      BR:
        description: 'Kernel Branch'
        required: true
        default: 'stable'        
      TREE:
        description: 'Kernel Tree'
        required: true
        default: 'https://github.com/SM4250-Dev/kernel_realme_RMX2195'
      AK3:
        description: 'Anykernel Tree'
        required: true
        default: 'https://github.com/UdyneO2/Anykernel'
      CLANG:
        description: 'clang compiler'
        required: true
        default: 'https://github.com/techyminati/android_prebuilts_clang_host_linux-x86_clang-6443078'
      AK3_BR:
        description: 'AK3 Branch'
        required: true
        default: 'RMX2195'
      NAME:
        description: 'Specify your kernel NAME.'
        required: true
        default: 'RMX2195-V1.1'
      DEVICE:
        description: 'Specify your Device Codename.'
        required: true
        default: 'RMX2195'
      KSU:
        description: 'KernelSU'
        required: true
        default: 'true'
        type: choice
        options:
        - true
        - false
      REL:
        description: 'Release repo'
        required: true
        default: 'SM4250-Dev/kernel_realme_RMX2195'
jobs:
  Build-Kernel:
    name: "🐎 Build kernel"
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 2
      fail-fast: false
    env:
      KDIR: Kernel-Build
      KNAME: ${{ inputs.NAME}}
      kernelRepo: ${{ inputs.TREE }}
      kernelBranch: ${{ inputs.BR }}
      DEVICE: ${{ inputs.DEVICE }}
      ANYKERNEL_NAME: Anykernel3
      ANYKERNEL_SOURCE: ${{ inputs.AK3 }}
      ANYKERNEL_SOURCE_BRANCH: ${{ inputs.AK3_BR }}
      DEFCONFIG_NAME: ${{ inputs.DEVICE }}_defconfig
      withKSUN: ${{ inputs.KSU }}
      ARCH: arm64
      OUT_DIR: out
      XCLANG: ${{ inputs.CLANG }}
      ROOT: /home/runner/work
    steps:
      - name: "✨ Create working dir"
        run: mkdir -p $KDIR

      - name: "⭐ Install prerequisites"
        run: |
          sudo apt-get update
          sudo apt update && sudo apt install bc  bison  build-essential  ccache   curl  flex  git libelf-dev libssl-dev lzop  python3  rsync unzip  zlib1g-dev gcc gcc-aarch64-linux-gnu gcc-arm-linux-gnueabi make libncurses5-dev libncursesw5-dev wget
      - name: "🌟 Clone kernel source => (${{ env.kernelRepo }})"
        working-directory: ./${{ env.KDIR }}
        run: |
          git clone --recursive --branch $kernelBranch $kernelRepo $KNAME --depth=1
          
      - name: "😋 Update KernelSU-Next"
        working-directory: ./${{ env.KDIR }}/${{ env.KNAME }}
        if: ${{ env.withKSUN == 'true' }}
        run: |
          cat ./arch/arm64/configs/${{ env.DEFCONFIG_NAME }} | grep KSU
          if grep -q "CONFIG_KSU" arch/arm64/configs/${{ env.DEFCONFIG_NAME }}; then
                    sed -i 's/# CONFIG_KSU is not set/CONFIG_KSU=y/g' arch/arm64/configs/${{ env.DEFCONFIG_NAME }}
                    sed -i 's/CONFIG_KSU=n/CONFIG_KSU=y/g' arch/arm64/configs/${{ env.DEFCONFIG_NAME }}
                else
                    echo "CONFIG_KSU=y" >> arch/arm64/configs/${{ env.DEFCONFIG_NAME }}
          fi
          curl -LSs "https://raw.githubusercontent.com/KernelSU-Next/KernelSU-Next/next/kernel/setup.sh" | bash -
          
      - name: "🎶 Build kernel"
        working-directory: ./${{ env.KDIR }}/${{ env.KNAME }}
        run: |
          export KBUILD_BUILD_USER="mnrdnn"
          export KBUILD_BUILD_HOST="github"
          export KBUILD_USER="mnrdnn"
          export KBUILD_HOST="github"
          sudo timedatectl set-timezone Asia/Jakarta
          timedatectl
          export TZ="Asia/Jakarta"
          export DATE="$(TZ=Asia/Jakarta date +%Y%m%d%H%M)"
          echo "DATE=$(TZ=Asia/Jakarta date +%Y%m%d%H%M)" >> $GITHUB_ENV
          git clone $XCLANG ~/toolchains/clang --depth=1 
          export CLANG_PATH=~/toolchains/clang/bin
          export PATH=${CLANG_PATH}:${PATH}
          export ARCH=arm64
          export SUBARCH=arm64
          export CROSS_COMPILE=aarch64-linux-gnu-
          export CROSS_COMPILE_ARM32=arm-linux-gnueabi-
          export CLANG_TRIPLE=aarch64-linux-gnu-
          echo "PATH Variable: $PATH"
          echo
          echo "Set DEFCONFIG"
          TIME="$(date "+%Y%m%d-%H%M%S")"
          START_TIME=$(date +%s)
          echo $START_TIME > /tmp/start_time.txt
          echo 
          make CC=clang AR=llvm-ar NM=llvm-nm OBJCOPY=llvm-objcopy OBJDUMP=llvm-objdump STRIP=llvm-strip O=out ${{ env.DEFCONFIG_NAME }}
          echo
          echo "Start building"
          echo 
          make CC=clang AR=llvm-ar NM=llvm-nm OBJCOPY=llvm-objcopy OBJDUMP=llvm-objdump STRIP=llvm-strip O=out -j$(nproc --all)
          echo
          echo "Build Succesfully"
          END_TIME=$(date +%s)
          echo $END_TIME > /tmp/end_time.txt
          
          git clone --depth=1 $ANYKERNEL_SOURCE -b $ANYKERNEL_SOURCE_BRANCH $ANYKERNEL_NAME && rm -rf $ANYKERNEL_NAME/.git $ANYKERNEL_NAME/.github
          if [[ -f $OUT_DIR/arch/$ARCH/boot/Image.gz ]]; then
            cp $OUT_DIR/arch/$ARCH/boot/Image.gz $ANYKERNEL_NAME/Image.gz
            mkdir -p /home/runner/work/upload/kernel
            cp $OUT_DIR/arch/$ARCH/boot/Image.gz /home/runner/work/upload/kernel
            echo -e "Image.gz found"
            cd $ANYKERNEL_NAME && zip -r9 ${{ env.ANYKERNEL_NAME }}-${{ env.DEVICE }}-$TIME.zip * -x .git README.md *placeholder
            mv ${{ env.ANYKERNEL_NAME }}-${{ env.DEVICE }}-$TIME.zip /home/runner/work/upload
            cd ..
          else
            echo -e "Image.gz not found"
          fi
          echo ""
          echo -e "Upload ${{ env.ANYKERNEL_NAME }}-${{ env.DEVICE }}-$TIME.zip"
          echo ""
      - name: "Notif tele"
        if : success()
        working-directory: ./${{ env.KDIR }}/${{ env.KNAME }}
        run: |
            export token=${{ secrets.TG_TOKEN }}
            export chat_id=${{ secrets.TG_ID }}
            export TID=${{ secrets.TG_TID }}
            START_TIME=$(cat /tmp/start_time.txt)
            END_TIME=$(cat /tmp/end_time.txt)
            # Hitung durasi
            DURATION=$((END_TIME - START_TIME))
            DURATION_FORMATTED=$(printf '%02d:%02d:%02d' $((DURATION/3600)) $((DURATION%3600/60)) $((DURATION%60)))
    
            CURRENT_TIME="$(date "+%Y%m%d-%H%M%S")"
            tg() {
                echo "- Sending message ..."
                curl -sX POST https://api.telegram.org/bot"${token}"/sendMessage -d chat_id="${chat_id}" -d message_thread_id="${TID}" -d parse_mode=Markdown -d disable_web_page_preview=true -d text="$1" &>/dev/null
                 }
            PESAN="*Upload Kernel Status* : Success ✅
            *Waktu Notifikasi* : \`$CURRENT_TIME\`
            *Waktu Build* : 
            • Start : \`$(date -d @$START_TIME "+%Y-%m-%d %H:%M:%S")\`
            • End   : \`$(date -d @$END_TIME "+%Y-%m-%d %H:%M:%S")\`
            • Durasi: \`$DURATION_FORMATTED\`

            🔗 *Link Download* : [Klik disini](https://github.com/${{ inputs.REL }}/releases/tag/${{ env.KNAME }})"
    
            tg "$PESAN"
      - uses: softprops/action-gh-release@v2
        with:
         token: ${{ secrets.GH_TOKEN }}
         repository: ${{ inputs.REL }}
         files: |
           /home/runner/work/upload/*.zip
         name: Update Kernel Build | ${{ env.ANYKERNEL_NAME }}-${{ env.DEVICE }}
         tag_name: ${{ env.KNAME }}
         body: |
          ### Release Notes:
          * Kernel compiled using clang 11.0.1
          * Thanks [github](https://github.com)
           ### Changelog ;
          * - bugs? [tell me](https://t.me/mnrdnn)
      - uses: actions/upload-artifact@v4
        with:
          name: ${{ env.ANYKERNEL_NAME }}-${{ env.DEVICE }}
          path: /home/runner/work/upload/kernel/

